const totalsData = {
  date: '',
  total_invested: 0,
  realized: {
    dividends: 0,
    transaction_cost: 0,
    value_pl: 0,
    forex_pl: 0,
    total_pl: 0,
    dividends_percentage: 0,
    transaction_cost_percentage: 0,
    value_pl_percentage: 0,
    forex_pl_percentage: 0,
    total_pl_percentage: 0,
  },
  unrealized: {
    total_cost: 0,
    total_value: 0,
    value_pl: 0,
    forex_pl: 0,
    total_pl: 0,
    value_pl_percentage: 0,
    forex_pl_percentage: 0,
    total_pl_percentage: 0,
  },
  combined: {
    value_pl: 0,
    forex_pl: 0,
    total_pl: 0,
    value_pl_percentage: 0,
    forex_pl_percentage: 0,
    total_pl_percentage: 0,
  },
  userid: '',
  id: '',
  _rid: '',
  _self: '/',
  _etag: '',
  _attachments: '',
  _ts: 0,
};

const stocksHeldData = {
  date: '',
  symbol: '',
  currency: '',
  fully_realized: false,
  partial_realized: false,
  realized: {
    cost_per_share_buy: 0,
    cost_per_share_buy_foreign: 0,
    cost_per_share_sell: 0,
    cost_per_share_sell_foreign: 0,
    buy_price: 0,
    buy_price_foreign: 0,
    sell_price: 0,
    sell_price_foreign: 0,
    average_buy_fx_rate: 0,
    average_sell_fx_rate: 0,
    quantity: 0,
    transaction_cost: 0,
    dividend: 0,
    total_dividends: 0,
    value_pl: 0,
    forex_pl: 0,
    total_pl: 0,
    value_pl_percentage: 0,
    forex_pl_percentage: 0,
    total_pl_percentage: 0,
  },
  unrealized: {
    cost_per_share: 0,
    cost_per_share_foreign: 0,
    total_cost: 0,
    total_cost_foreign: 0,
    average_fx_rate: 0,
    quantity: 0,
    open_value: 0,
    high_value: 0,
    low_value: 0,
    close_value: 0,
    total_value: 0,
    value_pl: 0,
    forex_pl: 0,
    total_pl: 0,
    total_pl_percentage: 0,
    value_pl_percentage: 0,
    forex_pl_percentage: 0,
  },
  combined: {
    value_pl: 0,
    forex_pl: 0,
    total_pl: 0,
    value_pl_percentage: 0,
    forex_pl_percentage: 0,
    dividend_pl_percentage: 0,
    transaction_cost_percentage: 0,
    total_pl_percentage: 0,
  },
  userid: '',
  id: '',
  _rid: '',
  _self: '',
  _etag: '',
  _attachments: '',
  _ts: 0,
};

export { totalsData, stocksHeldData };
